create table USERS (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(255) NOT NULL UNIQUE,
    PASS VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SALT VARCHAR(255) NOT NULL
);

create table ROLES (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PERMISSION VARCHAR(255) NOT NULL,
    RESOURCE VARCHAR(255) NOT NULL,
    USER_ID INT NOT NULL
);

CREATE TABLE ACCOUNTING (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ROLE_ID INT NOT NULL,
    AMOUNT INT NOT NULL,
    DATE_START DATE NOT NULL,
    DATE_END DATE NOT NULL

);

ALTER TABLE ROLES
    ADD FOREIGN KEY (USER_ID)
    REFERENCES USERS(ID);

ALTER TABLE ACCOUNTING
    ADD FOREIGN KEY (ROLE_ID)
    REFERENCES ROLES(ID);

INSERT INTO USERS (LOGIN, PASS, NAME, SALT) VALUES ( 'jdoe', '69bbf64c9f435cb9cd7e1855d8191994', 'John Doe', 'cmfu6ut076majch6msnki83ahj' );
INSERT INTO USERS (LOGIN, PASS, NAME, SALT) VALUES ( 'jrow', '71a6cc0020a901cd1366e62b79022321', 'Jane Row', 'tcbatb6d9pqb2nhvb3i7l2oj2i' );

INSERT INTO ROLES (PERMISSION, RESOURCE, USER_ID) VALUES ( 'READ', 'a', 1 );
INSERT INTO ROLES (PERMISSION, RESOURCE, USER_ID) VALUES ( 'WRITE', 'a.b', 2 );
INSERT INTO ROLES (PERMISSION, RESOURCE, USER_ID) VALUES ( 'EXECUTE', 'a.b.c', 1 );
INSERT INTO ROLES (PERMISSION, RESOURCE, USER_ID) VALUES ( 'EXECUTE', 'a.bc', 1 );